# These are supported funding model platforms

patreon: androidacy # Replace with a single Patreon username

custom: https://www.androidacy.com/donate/ # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
