# These are supported funding model platforms

patreon: linuxandria_xda # Replace with a single Patreon username

custom: https://paypal.me/linxuandria # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
