name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for your contribution! Please keep in mind I will get to this issue when I have a chance and logs and device information are required if you do not want your issue closed'
        pr-message: 'Thanks for your contribution! All pull requests must be meaningful and follwo general good coding practices. Also keep in mind I do not merge many pull requests!'
